stages:
  - build

deploy-job:
  stage: build
  only:
    - branches
  script:
#    Handy for debugging
    - whoami
    - hostname
    - pwd
    - mvn -v
#    Build via maven
    - mvn --batch-mode --errors -U clean deploy
  tags:
    - Java8-Nexus3
